name: rent_car_ui_design
description: "rent_car_ui_design"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/corvette_front.png
    - assets/corvette_back.png
    - assets/corvette_front2.png
    - assets/interior1.png
    - assets/interior2.png
    - assets/lambo_front.png
    - assets/lambo_back.png
    - assets/interior_lambo.png

